### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mitjajez**
Added Usage section

### CODE REVIEW

**Comment by jnvsor** [comment]
I don't think the styling information is needed - nor will it work if your site doesn't link a css file in the first place (Or include it in sass). Can you squash the rest into a single commit and update your PR?

**Comment by mitjajez** [comment]
Ah, sorry, now I see, actually, I separate `ul.menu > li {` part from your main.scss into `_sass/_menu.scss` and included back to keep `css/main.scss` clear on my page [_menu.scss](https://github.com/mitjajez/mitjajez.github.io/blob/master/_sass/_menu.scss).

So, should I separate this in PR too or clean styling out?

**Comment by mitjajez** [comment]
On my page I did that [_menu.scss](https://github.com/mitjajez/mitjajez.github.io/blob/master/_sass/_menu.scss).

**Comment by jnvsor** [comment]
Since the styling is completely up to the user (jdm just provides the classes) I think we should leave the styling part out.

Afterwards, could you squash your commits together so it comes in as one clean commit? (`git rebase -i`, then force push to your PR branch when it's squashed)

**Comment by mitjajez** [comment]
OK, so all changes are done now.

I never did squash. I did this PR over GitHub webpage, not with git tool.
I can do new clean PR or please guide me how to do it.
I also find out that this could be done [together with merging](https://help.github.com/articles/about-pull-request-merge-squashing/).

**Comment by jnvsor** [comment]
Squashed it myself - merged in ab2c15d1d9fb62ac847a99fb9490a3e32dcaa1b8

**Pull request closed without merging**
